@Web_HostAddress = http://localhost:5265

GET {{Web_HostAddress}}/api/admin/GetAllPolyclinics

###

GET {{Web_HostAddress}}/api/admin/GetAllHealthExaminations

###

POST {{Web_HostAddress}}/api/admin/GetDetails
Content-Type: application/json

{
  "Id": "e475a0ad-19bf-4dfe-723b-08dd3b17b33b"
}

###
